services:
  - type: web
    name: skin-disease-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
